name: mega_dot_pk
description: Mobile app for Mega Dot PK

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  intl: 0.16.0
  provider: 4.0.1
  url_launcher: 5.2.7
  google_fonts: 0.2.0
  firebase_auth: 0.15.3
  firebase_core: 0.4.3+1
  cupertino_icons: ^0.1.2
  extended_nested_scroll_view: 0.3.8
  flutter_advanced_networkimage: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/wordmark.png
