name: mega_dot_pk
description: Mobile app for Mega Dot PK

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.12.0+4
  intl: 0.16.0
  provider: 4.0.4
  url_launcher: 5.4.2
  google_fonts: 0.3.10
  firebase_auth: 0.15.5+2
  firebase_core: 0.4.4+3
  cupertino_icons: 0.1.3
  line_awesome_icons: 1.0.4+2
  extended_nested_scroll_view: 0.3.8
  flutter_advanced_networkimage: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/wordmark.png
